### ISSUE TITLE
Document view fixes

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#267] opened 2023-07-17 18:12 UTC
adjustments:
- [x] cursor color on dark mode
- [x] set line height to match standard nodes (24px/1.5rem)
- [x] don’t allow indenting paragraphs
- [x] disable checkboxes, clocks
- [x] use --color-text-placeholder for markdown syntax (serves same purpose of being visible but as unobtrusive as possible)

bugs:
- [x] command palette doesn't open when a document paragraph is selected (Unhandled Promise Rejection: TypeError: null is not an object (evaluating 't.editor'))

<img width="678" alt="image" src="https://github.com/treehousedev/treehouse/assets/1813419/896f7207-2fdf-4b12-87f9-deca79305b7a">

- [x] pasting text into an empty document node - text disappears
- [ ] TypeError when putting cursor in document node parent header (Unhandled Promise Rejection: TypeError: null is not an object (evaluating 't.editor')). With Document View open, put the cursor in the Document title/header at the top of the page.
now getting a slightly different message:

<img width="661" alt="image" src="https://github.com/treehousedev/treehouse/assets/1813419/7d716f51-7bb9-486c-adbc-1675671aec83">

- [x] select text + delete not working

chrome-specific issues:
- [x] with the cursor at the end of a document paragraph node, hit enter and start typing: new paragraph is created but no text appears (https://share.getcloudapp.com/eDuEXWdO - this time it was extra weird, i was mashing my keyboard and it only recorded a few characters...)
- [x] can't backspace through any document node text (when i tried this a second time, it put the cursor at the beginning of the node. so put the cursor anywhere in a document paragraph node, hit backspace once, and the cursor will go to the beginning of the node (nothing is deleted)

**Comment by progrium** [comment] 2023-07-17 22:40
determined node header error is not specific to document view, but any node you've opened/zoomed. since its unrelated and non-trivial, it can be a new issue. closing this one and will leave #246 open until confirmed good to go (outside this last, separate issue)

**Closed by progrium** 2023-07-17 22:40 UTC
